version: '3.1'

services:
  web:
    build: .
    environment:
      MONGODB_USERNAME: "${MONGODB_USERNAME}"
      MONGODB_PASSWORD: "${MONGODB_PASSWORD}"

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
